### PR TITLE
Style revamp mobile

### PR DESCRIPTION
**Pull request by adedayomoshood**
Mobile View

screenshot 2019-02-17 at 14 33 03

screenshot 2019-02-17 at 14 32 50

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
This looks great, can we have a dark mode background?
What do you think?

**Comment by adedayomoshood** [comment]
Work In Progress on that. Users will be able to switch to preferred mode Dark/Light

**Comment by BolajiAyodeji** [comment]
That would be awesome!
Well done :+1: +1

**Comment by shalvah** [comment]
This looks nice. Why is it in a separate PR from #14 , though? I think a single PR would be better, since you can't really change the desktop design without changing the mobile. It's practically the same code, plus media queries.

**Comment by shalvah** [comment]
Going to go ahead and close this. Let's keep this in #14.

**Comment by adedayomoshood** [comment]
> This looks nice. Why is it in a separate PR from #14 , though? I think a single PR would be better, since you can't really change the desktop design without changing the mobile. It's practically the same code, plus media queries.

This is an update of #14  it's better to keep this as this is more updated.

**Pull request closed without merging**
