### PR TITLE
Display user's tweet in Grid

### PR DESCRIPTION
**Pull request by BolajiOlajide**
## Description

Same as title.

screenshot 2019-02-16 at 3 39 05 am

### CODE REVIEW

**Comment by shalvah** [comment]
Thank you. +1 for the screenshot.

The different heights of the tweets make it look a bit odd. Is there anything we can do about that? Is bottom alignment the best?

Also, how does it look on mobile?

**Comment by BolajiOlajide** [comment]
Yeah, should have submitted it as a draft( (or WIP). The different heights of the card make it odd but I'm thinking if one can make it into the mosaic design such that they fit into themselves. The only problem with that is that it'll affect ordering.

I'll send a screenshot of mobile but basically, it's one column on mobile that goes all the way down.

**Comment by shalvah** [comment]
Okay. Ordering isn't really a major factor within years. We can tolerate
minor discrepancies in order.

**Comment by ooade** [comment]
It could be done with `column-count`. I did something like that [here](https://p1nit.herokuapp.com).

**Comment by BolajiOlajide** [comment]
@ooade I don't think `column-count` will do the trick here because the tweets are categorized by the year and you might have a column extremely long and others short. I'm drifting towards a `grid-auto-flow: dense` scenario but looking at how that will work for example with categories that have just 2 tweets.

I've been swamped with a number of things recently so you're welcome to try it out if you are chanced, if not I'll revisit this soonest and propose a solution with screenshots.

cc @shalvah

**Comment by shalvah** [comment]
Probably best to hold off on this for the time being.

**Pull request closed without merging**
