### PR TITLE
modifed project structure

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
I modified the project structure
- Change stylesheet to external
- moved images to `img` folder
- Added a new font
- Refactored some styles

image

### CODE REVIEW

**Comment by shalvah** [comment]
Good work. I'd rather keep the styles in the page though. I believe it makes the page load faster (no extra request for stylesheet).

**Comment by BolajiAyodeji** [comment]
> Good work. I'd rather keep the styles in the page though. I believe it makes the page load faster (no extra request for stylesheet).

Okay, would take it in.
The script also?
I see you made more changes also.

**Comment by shalvah** [comment]
I'm not sure you resolved conflicts correctly. Looks like the showError function is missing. Can you just copy and paste the JS code from master?

**Comment by BolajiAyodeji** [comment]
Okay, let me check!

**Comment by BolajiAyodeji** [comment]
@shalvah Its fixed now

**Comment by BolajiAyodeji** [comment]
Back to top feature;
image

**Comment by shalvah** [comment]
Cool!

**Comment by shalvah** [comment]
Sweet! Nice touch with the "Back to top" button.

**Pull request merged**
