### PR TITLE
Make form inputs more responsive

### PR DESCRIPTION
**Pull request by ccmelas**
1. Adds responsiveness to the search form.
2. Puts the styling into a separate css/main.css file

### CODE REVIEW

**Review by BolajiAyodeji — COMMENTED** [review]
We've already discussed having external sheets, we'd rather keep the styles in the page though, makes the page load faster.

You can leave the responsiveness, this should work with issue #6 
Good Job!

**Comment by ccmelas** [comment]
Ok. Putting back the styles.

**Comment by BolajiAyodeji** [comment]
Alright, Good job!

**Comment by shalvah** [comment]
Thanks for this. 

(PS. for visual changes, please include a screenshot with your PR. I'll add this to contribution guidelines.)

**Pull request merged**
